// <auto-generated />
using System;
using FleetTelemetry.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetTelemetry.Data.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20260713121935_AddVehicleDisplayNumber")]
    partial class AddVehicleDisplayNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetTelemetry.Data.Entities.TelemetrySnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CargoLoad")
                        .HasColumnType("integer")
                        .HasColumnName("cargo_load");

                    b.Property<int?>("EngineHealth")
                        .HasColumnType("integer")
                        .HasColumnName("engine_health");

                    b.Property<double?>("FuelPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("fuel_percent");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double?>("SpeedKph")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_kph");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<int?>("TempCelsius")
                        .HasColumnType("integer")
                        .HasColumnName("temp_celsius");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_telemetry_vehicle_time");

                    b.ToTable("telemetry_snapshots", (string)null);
                });

            modelBuilder.Entity("FleetTelemetry.Data.Entities.VehicleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("display_number");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("driver_name");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.HasKey("Id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("FleetTelemetry.Data.Entities.VehicleLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("level");

                    b.Property<DateTime>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "LoggedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_logs_vehicle_time");

                    b.ToTable("vehicle_logs", (string)null);
                });

            modelBuilder.Entity("FleetTelemetry.Data.Entities.TelemetrySnapshotEntity", b =>
                {
                    b.HasOne("FleetTelemetry.Data.Entities.VehicleEntity", "Vehicle")
                        .WithMany("Snapshots")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FleetTelemetry.Data.Entities.VehicleLogEntity", b =>
                {
                    b.HasOne("FleetTelemetry.Data.Entities.VehicleEntity", "Vehicle")
                        .WithMany("Logs")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FleetTelemetry.Data.Entities.VehicleEntity", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
