apiVersion: v1 # Secret like Service, is a core Kubernetes type, so it's in the original v1 API group with no prefix
kind: Secret #  declares the object type.
metadata:
  name: {{ include "iiot-fleet-app.fullname" . }}-backend
  labels:
    {{- include "iiot-fleet-app.labels" . | nindent 4 }}
type: Opaque # the generic catch-all type
data: # Kubernetes Secret, values under data: must be base64-encoded by whoever writes the manifest 
  ConnectionStrings__Fleet: {{ printf "Host=%s-db;Port=%v;Database=fleet_telemetry;Username=postgres;Password=%s;" (include "iiot-fleet-app.fullname" .) .Values.db.port .Values.db.password | b64enc }} # %s — a string placeholder, %v — a general-purpose "default format" placeholder, The three arguments, matched in order to the three % verbs and the entire assembled connection string is piped into Helm's b64enc function, which base64-encodes it.
