-- =============================================================================
-- IIoT Fleet Telemetry System — PostgreSQL Setup Script
-- =============================================================================
-- Run this script as a PostgreSQL superuser (e.g. postgres) to create the
-- database and all tables from scratch.
--
-- Usage:
--   psql -U postgres -f docs/database/setup.sql
--
-- Or connect to an existing DB and run individual sections as needed.
-- =============================================================================


-- =============================================================================
-- 1. DATABASE
-- =============================================================================

-- Create the database (run as superuser outside of a transaction block)
-- Skip if the database already exists.
SELECT 'CREATE DATABASE fleet_telemetry'
WHERE NOT EXISTS (
    SELECT FROM pg_database WHERE datname = 'fleet_telemetry'
)\gexec

-- Connect to the database
\c fleet_telemetry


-- =============================================================================
-- 2. EXTENSIONS
-- =============================================================================

-- Enable pgcrypto for UUID generation (optional, reserved for future use)
-- CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- =============================================================================
-- 3. TABLES
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 3.1 vehicles
-- Stores persistent metadata for every vehicle in the fleet.
-- Populated once on backend startup by DbSeeder.cs (idempotent).
-- Runtime telemetry (position, speed, fuel, etc.) lives in-memory in
-- TelemetrySimulationService — only metadata persists here.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vehicles (
    -- Business key: "VEH-00000" through "VEH-09999"
    id          VARCHAR(20)  NOT NULL,

    -- Driver assigned to this vehicle (from the 12-name pool in DbSeeder)
    driver_name VARCHAR(100) NOT NULL,

    -- Vehicle model: "NV Cargo" or "Apex Hauler"
    model       VARCHAR(50)  NOT NULL,

    -- Timestamp when this row was inserted (UTC)
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_vehicles PRIMARY KEY (id)
);

COMMENT ON TABLE  vehicles             IS 'Persistent fleet vehicle metadata. Seeded with 10,000 rows on first startup.';
COMMENT ON COLUMN vehicles.id          IS 'Vehicle business key, e.g. "VEH-00001". Matches in-memory simulation ID.';
COMMENT ON COLUMN vehicles.driver_name IS 'Driver name assigned to this vehicle (cycles through 12-name pool).';
COMMENT ON COLUMN vehicles.model       IS '"NV Cargo" or "Apex Hauler".';
COMMENT ON COLUMN vehicles.created_at  IS 'Row insert timestamp (UTC). Set by DB default, not application.';


-- -----------------------------------------------------------------------------
-- 3.2 vehicle_logs
-- Event log entries generated by the simulation engine.
-- Each vehicle retains up to 50 in-memory log entries; this table is for
-- durable storage of telemetry events (status changes, alerts, etc.).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vehicle_logs (
    -- Surrogate primary key (auto-increment)
    id         BIGSERIAL    NOT NULL,

    -- References vehicles.id
    vehicle_id VARCHAR(20)  NOT NULL,

    -- UTC timestamp of the log event
    logged_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- Severity: INFO | WARN | ERROR
    level      VARCHAR(10)  NOT NULL DEFAULT 'INFO',

    -- Human-readable event description
    message    TEXT         NOT NULL DEFAULT '',

    CONSTRAINT pk_vehicle_logs        PRIMARY KEY (id),
    CONSTRAINT fk_logs_vehicle        FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
);

COMMENT ON TABLE  vehicle_logs            IS 'Durable event log for vehicle telemetry alerts and status changes.';
COMMENT ON COLUMN vehicle_logs.id         IS 'Auto-incrementing surrogate key.';
COMMENT ON COLUMN vehicle_logs.vehicle_id IS 'FK to vehicles.id.';
COMMENT ON COLUMN vehicle_logs.logged_at  IS 'UTC timestamp of the event.';
COMMENT ON COLUMN vehicle_logs.level      IS 'Severity level: INFO, WARN, or ERROR.';
COMMENT ON COLUMN vehicle_logs.message    IS 'Event description, e.g. "Overspeed detected: 92 kph".';


-- -----------------------------------------------------------------------------
-- 3.3 telemetry_snapshots
-- Point-in-time snapshots of vehicle telemetry.
-- Written periodically by the simulation service (future sprint).
-- Useful for historical trending, analytics, and replay.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS telemetry_snapshots (
    -- Surrogate primary key (auto-increment)
    id            BIGSERIAL        NOT NULL,

    -- References vehicles.id
    vehicle_id    VARCHAR(20)      NOT NULL,

    -- UTC timestamp of this snapshot
    recorded_at   TIMESTAMPTZ      NOT NULL DEFAULT NOW(),

    -- GPS coordinates
    latitude      DOUBLE PRECISION,
    longitude     DOUBLE PRECISION,

    -- Fuel level as a percentage (0.0 – 100.0)
    fuel_percent  DOUBLE PRECISION,

    -- Current speed in km/h
    speed_kph     DOUBLE PRECISION,

    -- Engine health score (0 = perfect, 100 = critical)
    engine_health INT,

    -- Engine/ambient temperature in degrees Celsius
    temp_celsius  INT,

    -- Cargo weight in kilograms
    cargo_load    INT,

    -- Vehicle status at snapshot time: active | warning | danger | offline
    status        VARCHAR(10),

    CONSTRAINT pk_telemetry_snapshots   PRIMARY KEY (id),
    CONSTRAINT fk_snapshot_vehicle      FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
);

COMMENT ON TABLE  telemetry_snapshots              IS 'Time-series snapshots of vehicle telemetry for historical analysis.';
COMMENT ON COLUMN telemetry_snapshots.id           IS 'Auto-incrementing surrogate key.';
COMMENT ON COLUMN telemetry_snapshots.vehicle_id   IS 'FK to vehicles.id.';
COMMENT ON COLUMN telemetry_snapshots.recorded_at  IS 'UTC timestamp of the snapshot.';
COMMENT ON COLUMN telemetry_snapshots.latitude     IS 'GPS latitude (San Francisco bbox: 37.70 – 37.81).';
COMMENT ON COLUMN telemetry_snapshots.longitude    IS 'GPS longitude (San Francisco bbox: -122.52 to -122.35).';
COMMENT ON COLUMN telemetry_snapshots.fuel_percent IS 'Fuel level 0.0 – 100.0 percent.';
COMMENT ON COLUMN telemetry_snapshots.speed_kph    IS 'Speed in kilometers per hour.';
COMMENT ON COLUMN telemetry_snapshots.engine_health IS 'Engine health score 0 (perfect) to 100 (critical failure).';
COMMENT ON COLUMN telemetry_snapshots.temp_celsius  IS 'Engine temperature in degrees Celsius.';
COMMENT ON COLUMN telemetry_snapshots.cargo_load    IS 'Cargo weight in kilograms.';
COMMENT ON COLUMN telemetry_snapshots.status        IS 'Vehicle status: active | warning | danger | offline.';


-- =============================================================================
-- 4. INDEXES
-- =============================================================================

-- vehicle_logs: most queries are "get last N logs for a vehicle"
CREATE INDEX IF NOT EXISTS idx_logs_vehicle_time
    ON vehicle_logs (vehicle_id, logged_at DESC);

-- telemetry_snapshots: most queries are "get recent snapshots for a vehicle"
CREATE INDEX IF NOT EXISTS idx_telemetry_vehicle_time
    ON telemetry_snapshots (vehicle_id, recorded_at DESC);

-- telemetry_snapshots: time-range queries across all vehicles (analytics)
CREATE INDEX IF NOT EXISTS idx_telemetry_recorded_at
    ON telemetry_snapshots (recorded_at DESC);

-- vehicle_logs: filter by severity level
CREATE INDEX IF NOT EXISTS idx_logs_level
    ON vehicle_logs (level);


-- =============================================================================
-- 5. VERIFICATION QUERIES
-- =============================================================================
-- Run these after setup to verify the schema is correct.

-- List all tables
-- \dt

-- Check table structure
-- \d vehicles
-- \d vehicle_logs
-- \d telemetry_snapshots

-- Count rows (after seeding)
-- SELECT COUNT(*) FROM vehicles;               -- Expected: 10000 after startup
-- SELECT COUNT(*) FROM vehicle_logs;            -- Expected: 0 initially
-- SELECT COUNT(*) FROM telemetry_snapshots;     -- Expected: 0 initially

-- Sample vehicle rows
-- SELECT id, driver_name, model, created_at FROM vehicles LIMIT 5;


-- =============================================================================
-- 6. TEARDOWN (use with caution — destroys all data)
-- =============================================================================
-- DROP TABLE IF EXISTS telemetry_snapshots CASCADE;
-- DROP TABLE IF EXISTS vehicle_logs CASCADE;
-- DROP TABLE IF EXISTS vehicles CASCADE;
-- DROP DATABASE IF EXISTS fleet_telemetry;
